name: ${project.name}
version: ${buildNumber}
description: ${project.description}
author: ${project.organization.name}
website: ${project.organization.url}

main: com.almuramc.aqualock.bukkit.AqualockPlugin
depend: [Spout, Vault]
load: POSTWORLD

commands:
    aqualock:
        description: Manage Aqualock
        usage: /aqualock [command] [arguments]